language: java

before_install:
  - chmod +x gradlew
  - chmod -R +x travis_scripts

## Default install
#install:
#  - ./gradlew assemble

## Default script
#script:
#  - ./gradlew check

before_deploy:
  - echo "Creating release tag if necessary"
  - ./travis_scripts/tag_if_release.sh
  - echo "git describe $(git describe)"

deploy:
  - provider: script
    skip_cleanup: true
    script: ./travis_scripts/snapshotDeploy.sh
    on:
      branch: master
      condition: "$(cat 'version.txt') =~ ^.*SNAPSHOT$"
  - provider: script
    skip_cleanup: true
    script: ./travis_scripts/releaseDeploy.sh
    on:
      branch: master
      condition: "! $(cat 'version.txt') =~ ^.*SNAPSHOT$"

after_deploy:
  - echo "Pushing tags (if necessary)"
  - ./travis_scripts/push_tag_if_release.sh
  - echo "Setting next snapshot (if necessary)"
  - ./travis_scripts/set_next_snapshot.sh